### ISSUE TITLE
readthedocs link in README is broken

### ISSUE THREAD

**Issue by willkg** [pybee/galley#3] opened 2015-01-22 14:13 UTC
The readthedocs link in the README is an HTTP 404. I don't know what the working link should be.

**Comment by freakboy3742** [comment] 2015-01-22 23:45
Thanks for the report - many of the links and explanations int he docs are broken, because this was released "just to get it out there". It wasn't really ready for release, but @ericholscher asked to see it, so I pushed the repository public. 

Closing this as a dupe of #2, since it's a generic problem with the docs.

**Closed by freakboy3742** 2015-01-22 23:45 UTC

**Comment by willkg** [comment] 2015-01-23 01:58
No worries! I appreciate you releasing it like this. I just wanted to add a todo item in case no one saw, yet.

**Comment by lurch** [comment] 2016-06-14 13:39
18 months later, and the docs-link still hasn't been fixed? :-(

**Comment by freakboy3742** [comment] 2016-06-15 05:48
@lurch: Let me save you the suspense: It probably isn't worth installing. As my previous comment says, I released this "just to get it out there". It needs a lot more work. I agree that this could probably be communicated better on the project homepage; but that is, in itself, more work. 

I'm hoping to find time to rationalise the BeeWare project pages in the near future that will hopefully improve this communication. In the meantime, if you want to submit a pull request, I'll gladly merge it.

**Comment by lurch** [comment] 2016-06-15 10:17
> @lurch: Let me save you the suspense: It probably isn't worth installing.

Haha, fair enough :)
